# Generated by Django 5.0.6 on 2026-05-22 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("master", "0003_employeehousing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalDestination",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=150)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=50)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MedicalReason",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("code", models.SlugField(unique=True)),
                ("name_pt", models.CharField(max_length=100)),
                ("name_jp", models.CharField(max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name_pt"],
            },
        ),
        migrations.CreateModel(
            name="MedicalRequest",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Baixa"),
                            ("medium", "Media"),
                            ("urgent", "Urgente"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("has_vehicle", models.BooleanField(default=False)),
                ("needs_transport", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Solicitado"),
                            ("triaged", "Triado"),
                            ("in_progress", "Em atendimento"),
                            ("completed", "Concluido"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField()),
                ("triaged_at", models.DateTimeField(blank=True, null=True)),
                ("started_service_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medical_requests_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medical_requests_completed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medical_requests",
                        to="medical.medicaldestination",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medical_requests",
                        to="master.employee",
                    ),
                ),
                (
                    "reason",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medical_requests",
                        to="medical.medicalreason",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medical_requests_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicalRequestEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_from",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("requested", "Solicitado"),
                            ("triaged", "Triado"),
                            ("in_progress", "Em atendimento"),
                            ("completed", "Concluido"),
                            ("cancelled", "Cancelado"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status_to",
                    models.CharField(
                        choices=[
                            ("requested", "Solicitado"),
                            ("triaged", "Triado"),
                            ("in_progress", "Em atendimento"),
                            ("completed", "Concluido"),
                            ("cancelled", "Cancelado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="medical.medicalrequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medical_request_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SymptomType",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("code", models.SlugField(unique=True)),
                ("name_pt", models.CharField(max_length=100)),
                ("name_jp", models.CharField(max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name_pt"],
            },
        ),
        migrations.CreateModel(
            name="MedicalRequestSymptom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="symptoms",
                        to="medical.medicalrequest",
                    ),
                ),
                (
                    "symptom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="request_symptoms",
                        to="medical.symptomtype",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="medicalrequest",
            index=models.Index(fields=["status"], name="medical_med_status_31fd72_idx"),
        ),
        migrations.AddIndex(
            model_name="medicalrequest",
            index=models.Index(
                fields=["severity"], name="medical_med_severit_99bef0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicalrequest",
            index=models.Index(
                fields=["requested_at"], name="medical_med_request_eebaf8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicalrequest",
            index=models.Index(
                fields=["employee"], name="medical_med_employe_e8360d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicalrequest",
            index=models.Index(
                fields=["assigned_to"], name="medical_med_assigne_6e4ff4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicalrequestevent",
            index=models.Index(
                fields=["status_to"], name="medical_med_status__2f2281_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicalrequestevent",
            index=models.Index(
                fields=["created_at"], name="medical_med_created_b4a307_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="medicalrequestsymptom",
            constraint=models.UniqueConstraint(
                fields=("request", "symptom"), name="unique_medical_request_symptom"
            ),
        ),
    ]
