# Generated by Django 5.0.6 on 2026-05-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_seed_initial_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="language",
            field=models.CharField(
                choices=[("pt-BR", "Português (Brasil)"), ("ja-JP", "日本語")],
                default="pt-BR",
                max_length=10,
            ),
        ),
    ]
