# Generated by Django 5.0.6 on 2025-10-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "employee_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name_jp", models.CharField(max_length=100)),
                ("name_en", models.CharField(max_length=100)),
                ("joined_imc", models.DateField(blank=True, null=True)),
                ("end_work", models.DateField(blank=True, null=True)),
                ("retired", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("gender_code", models.CharField(blank=True, max_length=10)),
                ("gender", models.CharField(blank=True, max_length=10)),
                ("shift", models.CharField(blank=True, max_length=20)),
                ("workplace_cd", models.CharField(blank=True, max_length=20)),
                ("workplace_name", models.CharField(blank=True, max_length=100)),
                ("rank", models.CharField(blank=True, max_length=10)),
                ("site_cd", models.CharField(blank=True, max_length=20)),
                ("site_abbr", models.CharField(blank=True, max_length=50)),
                ("nationality", models.CharField(blank=True, max_length=50)),
                ("hourly_rate", models.IntegerField(blank=True, null=True)),
                ("new_joined", models.DateField(blank=True, null=True)),
                ("months_worked", models.IntegerField(blank=True, null=True)),
                ("billing_rate", models.CharField(blank=True, max_length=20)),
                ("rejoined", models.BooleanField(default=False)),
                ("joined_fa", models.DateField(blank=True, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("internal_name", models.CharField(blank=True, max_length=100)),
                ("name_kana", models.CharField(blank=True, max_length=100)),
                ("process", models.CharField(blank=True, max_length=50)),
                ("name_cd", models.CharField(blank=True, max_length=50)),
                ("active_end_month", models.BooleanField(default=False)),
                ("building_floor", models.CharField(blank=True, max_length=20)),
                ("years_elapsed", models.IntegerField(blank=True, null=True)),
                ("months_elapsed", models.IntegerField(blank=True, null=True)),
                ("contract_type", models.CharField(blank=True, max_length=20)),
                ("manager_flag", models.BooleanField(default=False)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("ordia_number", models.CharField(blank=True, max_length=50)),
                ("dispatch_start", models.DateField(blank=True, null=True)),
                ("employee_cd", models.CharField(blank=True, max_length=20)),
                ("office_cd", models.CharField(blank=True, max_length=20)),
                ("total_hourly", models.IntegerField(blank=True, null=True)),
                ("elapsed_str", models.CharField(blank=True, max_length=20)),
                ("entry_type", models.CharField(blank=True, max_length=20)),
                ("view_flag", models.BooleanField(default=False)),
                ("hire_type", models.CharField(blank=True, max_length=20)),
                ("ic_card", models.CharField(blank=True, max_length=50)),
                ("imc_card", models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
