# Generated by Django 5.0.6 on 2025-10-05 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("label_pt", models.CharField(max_length=50)),
                ("label_jp", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="BuildingFloor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("label_pt", models.CharField(max_length=50)),
                ("label_jp", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("label_pt", models.CharField(max_length=50)),
                ("label_jp", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="EntryType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("label_pt", models.CharField(max_length=50)),
                ("label_jp", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Gender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("label_pt", models.CharField(max_length=50)),
                ("label_jp", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="HireType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("label_pt", models.CharField(max_length=50)),
                ("label_jp", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Nationality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name_pt", models.CharField(max_length=100)),
                ("name_jp", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("label_pt", models.CharField(max_length=50)),
                ("label_jp", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Rejoined",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=2, unique=True)),
                ("label_pt", models.CharField(max_length=50)),
                ("label_jp", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("label_pt", models.CharField(max_length=50)),
                ("label_jp", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="employee",
            name="billing_rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="master.billingrate",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="building_floor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="master.buildingfloor",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="master.department",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="entry_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="master.entrytype",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="master.gender",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="hire_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="master.hiretype",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="nationality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="master.nationality",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="process",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="master.process",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="rejoined",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="master.rejoined",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="master.shift",
            ),
        ),
    ]
