# Generated by Django 5.0.6 on 2025-10-06 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0002_billingrate_buildingfloor_department_entrytype_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeHousing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_cd", models.CharField(blank=True, max_length=50)),
                ("apartment_name", models.CharField(blank=True, max_length=100)),
                ("room_number", models.CharField(blank=True, max_length=20)),
                ("r", models.IntegerField(blank=True, null=True)),
                ("p", models.IntegerField(blank=True, null=True)),
                ("utilities", models.IntegerField(blank=True, null=True)),
                ("dgs", models.IntegerField(blank=True, null=True)),
                ("monthly_payment", models.IntegerField(blank=True, null=True)),
                ("management_fee", models.IntegerField(blank=True, null=True)),
                ("fixed_fee", models.IntegerField(blank=True, null=True)),
                ("parking_fee", models.IntegerField(blank=True, null=True)),
                ("lga", models.IntegerField(blank=True, null=True)),
                ("rent", models.IntegerField(blank=True, null=True)),
                ("collection_amount", models.IntegerField(blank=True, null=True)),
                ("move_in_date", models.DateField(blank=True, null=True)),
                ("move_out_date", models.DateField(blank=True, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("bus_stop", models.CharField(blank=True, max_length=100)),
                ("bus_number", models.CharField(blank=True, max_length=50)),
                ("office_cd", models.CharField(blank=True, max_length=50)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="housing_records",
                        to="master.employee",
                    ),
                ),
            ],
        ),
    ]
