# Generated by Django 5.0.6 on 2026-05-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0003_employeehousing"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="five_two_off_days",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="employee",
            name="nickname",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="operational_category",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("relief", "Relief"),
                    ("trainee", "Trainee"),
                    ("trainer", "Trainer"),
                    ("kl", "KL"),
                    ("gl", "GL"),
                    ("supervisor", "Supervisor"),
                    ("manager", "Manager"),
                    ("staff", "Staff"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="operational_memo",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="organization_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="rotation_group",
            field=models.CharField(
                blank=True, choices=[("A", "A"), ("B", "B"), ("C", "C")], max_length=1
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="shift_type",
            field=models.CharField(
                choices=[("day", "Day"), ("night", "Night"), ("flexible", "Flexible")],
                default="day",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="work_pattern",
            field=models.CharField(
                choices=[("4x2", "4x2"), ("5x2", "5x2"), ("manual", "Manual")],
                default="4x2",
                max_length=10,
            ),
        ),
    ]
