# Generated by Django 5.0.6 on 2026-05-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0004_employee_five_two_off_days_employee_nickname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="operational_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("normal", "Normal"),
                    ("relief", "Relief"),
                    ("trainee", "Trainee"),
                    ("trainer", "Trainer"),
                    ("kl", "KL"),
                    ("gl", "GL"),
                    ("supervisor", "Supervisor"),
                    ("manager", "Manager"),
                    ("staff", "Staff"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="shift_type",
            field=models.CharField(
                blank=True,
                choices=[("day", "Day"), ("night", "Night"), ("flexible", "Flexible")],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="work_pattern",
            field=models.CharField(
                blank=True,
                choices=[("4x2", "4x2"), ("5x2", "5x2"), ("manual", "Manual")],
                default="",
                max_length=10,
            ),
        ),
    ]
