# Generated by Codex on 2026-05-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


INITIAL_CATEGORIES = {
    "shirt": "Camiseta",
    "pants": "Calca",
    "cap": "Bone",
    "jacket": "Jaqueta",
    "other": "Outros",
}


def seed_categories_and_migrate_items(apps, schema_editor):
    UniformCategory = apps.get_model("inventory", "UniformCategory")
    UniformItem = apps.get_model("inventory", "UniformItem")

    categories = {}
    for code, name in INITIAL_CATEGORIES.items():
        category, _ = UniformCategory.objects.get_or_create(
            code=code,
            defaults={
                "name": name,
                "description": "Categoria inicial migrada do cadastro fixo.",
                "is_active": True,
            },
        )
        categories[code] = category

    fallback = categories["other"]
    for item in UniformItem.objects.all():
        item.category_ref = categories.get(item.category, fallback)
        item.save(update_fields=["category_ref"])


def restore_item_category_codes(apps, schema_editor):
    UniformItem = apps.get_model("inventory", "UniformItem")

    for item in UniformItem.objects.select_related("category").all():
        item.category_code = item.category.code if item.category_id else "other"
        item.save(update_fields=["category_code"])


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UniformCategory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("code", models.SlugField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Uniform category",
                "verbose_name_plural": "Uniform categories",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="uniformitem",
            name="category_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="inventory.uniformcategory",
            ),
        ),
        migrations.RunPython(seed_categories_and_migrate_items, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name="uniformitem",
            name="inventory_u_categor_ee64a3_idx",
        ),
        migrations.RemoveField(
            model_name="uniformitem",
            name="category",
        ),
        migrations.RenameField(
            model_name="uniformitem",
            old_name="category_ref",
            new_name="category",
        ),
        migrations.AlterField(
            model_name="uniformitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="inventory.uniformcategory",
            ),
        ),
        migrations.AddIndex(
            model_name="uniformitem",
            index=models.Index(fields=["category"], name="inventory_u_categor_46729e_idx"),
        ),
    ]
