# Generated by Django 5.0.6 on 2026-05-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_uniformcategory_item_category_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="uniformitem",
            name="average_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="uniformitem",
            name="average_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="uniformitem",
            name="unit_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="uniformrequest",
            name="request_type",
            field=models.CharField(
                choices=[("donation", "Doacao"), ("purchase", "Compra")],
                default="donation",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="uniformrequestitem",
            name="total_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="uniformrequestitem",
            name="unit_cost_snapshot",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="uniformrequest",
            name="reason",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
