# Generated by Django 5.0.6 on 2026-05-22 10:16

from django.db import migrations, models


INITIAL_LABELS = {
    "shirt": ("Camiseta", "Tシャツ"),
    "pants": ("Calca", "ズボン"),
    "cap": ("Bone", "帽子"),
    "jacket": ("Jaqueta", "ジャケット"),
    "other": ("Outros", "その他"),
}


def populate_category_labels(apps, schema_editor):
    UniformCategory = apps.get_model("inventory", "UniformCategory")

    for category in UniformCategory.objects.all():
        label_pt, label_jp = INITIAL_LABELS.get(
            category.code,
            (category.name, category.name),
        )
        if not category.label_pt:
            category.label_pt = label_pt
        if not category.label_jp:
            category.label_jp = label_jp
        category.save(update_fields=["label_pt", "label_jp"])


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0003_uniformitem_average_cost_uniformitem_average_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uniformcategory",
            options={
                "ordering": ["label_pt", "name"],
                "verbose_name": "Uniform category",
                "verbose_name_plural": "Uniform categories",
            },
        ),
        migrations.AddField(
            model_name="uniformcategory",
            name="label_jp",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="uniformcategory",
            name="label_pt",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(populate_category_labels, migrations.RunPython.noop),
    ]
