# Generated by Django 5.0.6 on 2026-05-22 10:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


ATTENDANCE_STATUS_SEEDS = [
    {
        "code": "work",
        "label_pt": "Trabalho",
        "label_jp": "出勤",
        "color": "#dbeafe",
        "is_working_day": True,
        "is_absence": False,
        "is_paid_leave": False,
    },
    {
        "code": "off",
        "label_pt": "Folga",
        "label_jp": "休",
        "color": "#e5e7eb",
        "is_working_day": False,
        "is_absence": False,
        "is_paid_leave": False,
    },
    {
        "code": "paid_leave",
        "label_pt": "Yukyu",
        "label_jp": "有休",
        "color": "#dcfce7",
        "is_working_day": False,
        "is_absence": False,
        "is_paid_leave": True,
    },
    {
        "code": "absence",
        "label_pt": "Falta",
        "label_jp": "欠勤",
        "color": "#fee2e2",
        "is_working_day": False,
        "is_absence": True,
        "is_paid_leave": False,
    },
    {
        "code": "late",
        "label_pt": "Atraso",
        "label_jp": "遅刻",
        "color": "#fef3c7",
        "is_working_day": True,
        "is_absence": False,
        "is_paid_leave": False,
    },
    {
        "code": "early_leave",
        "label_pt": "Saida antecipada",
        "label_jp": "早退",
        "color": "#ffedd5",
        "is_working_day": True,
        "is_absence": False,
        "is_paid_leave": False,
    },
    {
        "code": "training",
        "label_pt": "Treinamento",
        "label_jp": "研修",
        "color": "#ede9fe",
        "is_working_day": True,
        "is_absence": False,
        "is_paid_leave": False,
    },
]


WORK_TIME_CODE_SEEDS = [
    {
        "code": "regular",
        "label_pt": "Normal",
        "label_jp": "定時",
        "color": "#dbeafe",
        "affects_overtime": False,
    },
    {
        "code": "overtime",
        "label_pt": "Hora extra",
        "label_jp": "残業",
        "color": "#fef3c7",
        "affects_overtime": True,
    },
    {
        "code": "holiday_work",
        "label_pt": "Trabalho em folga",
        "label_jp": "休日出勤",
        "color": "#fee2e2",
        "affects_overtime": True,
    },
]


def seed_operations_master_data(apps, schema_editor):
    AttendanceStatus = apps.get_model("operations", "AttendanceStatus")
    WorkTimeCode = apps.get_model("operations", "WorkTimeCode")

    for seed in ATTENDANCE_STATUS_SEEDS:
        AttendanceStatus.objects.update_or_create(
            code=seed["code"],
            defaults={**seed, "is_active": True},
        )

    for seed in WORK_TIME_CODE_SEEDS:
        WorkTimeCode.objects.update_or_create(
            code=seed["code"],
            defaults={**seed, "is_active": True},
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("master", "0003_employeehousing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceStatus",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("code", models.SlugField(unique=True)),
                ("label_pt", models.CharField(max_length=100)),
                ("label_jp", models.CharField(max_length=100)),
                ("color", models.CharField(blank=True, max_length=20)),
                ("is_working_day", models.BooleanField(default=True)),
                ("is_absence", models.BooleanField(default=False)),
                ("is_paid_leave", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance status",
                "verbose_name_plural": "Attendance statuses",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyOperationCalendar",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2100),
                        ]
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operation_calendars",
                        to="master.department",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operation_calendars",
                        to="master.process",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operation_calendars",
                        to="master.shift",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month", "department"],
            },
        ),
        migrations.CreateModel(
            name="CalendarPrintPreset",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "paper_size",
                    models.CharField(
                        choices=[("A4", "A4"), ("A3", "A3")], default="A4", max_length=5
                    ),
                ),
                (
                    "orientation",
                    models.CharField(
                        choices=[("portrait", "Portrait"), ("landscape", "Landscape")],
                        default="landscape",
                        max_length=20,
                    ),
                ),
                (
                    "scale_percent",
                    models.PositiveSmallIntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(200),
                        ],
                    ),
                ),
                ("show_colors", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="print_presets",
                        to="operations.monthlyoperationcalendar",
                    ),
                ),
            ],
            options={
                "ordering": ["calendar", "paper_size", "orientation"],
            },
        ),
        migrations.CreateModel(
            name="CalendarEmployeeAssignment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "operational_category",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("relief", "Relief"),
                            ("trainer", "Trainer"),
                            ("koutei_leader", "Koutei leader"),
                            ("gl", "GL"),
                            ("supervisor", "Supervisor"),
                            ("manager", "Manager"),
                            ("director", "Director"),
                        ],
                        default="normal",
                        max_length=30,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operation_calendar_assignments",
                        to="master.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="operations.monthlyoperationcalendar",
                    ),
                ),
            ],
            options={
                "ordering": ["calendar", "display_order", "employee"],
            },
        ),
        migrations.CreateModel(
            name="OperationalPosition",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("code", models.CharField(max_length=50)),
                ("name_pt", models.CharField(max_length=100)),
                ("name_jp", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "building_floor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operational_positions",
                        to="master.buildingfloor",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_positions",
                        to="master.department",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["department", "code"],
            },
        ),
        migrations.CreateModel(
            name="PositionDailyRequirement",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("date", models.DateField()),
                ("required_headcount", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position_requirements",
                        to="operations.monthlyoperationcalendar",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_requirements",
                        to="operations.operationalposition",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["calendar", "date", "position"],
            },
        ),
        migrations.CreateModel(
            name="WorkTimeCode",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("code", models.SlugField(unique=True)),
                ("label_pt", models.CharField(max_length=100)),
                ("label_jp", models.CharField(max_length=100)),
                ("color", models.CharField(blank=True, max_length=20)),
                ("affects_overtime", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="CalendarDayCell",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("date", models.DateField()),
                ("overtime_minutes", models.PositiveIntegerField(default=0)),
                ("memo", models.TextField(blank=True)),
                ("raw_value", models.CharField(blank=True, max_length=255)),
                (
                    "attendance_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="day_cells",
                        to="operations.attendancestatus",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_cells",
                        to="operations.calendaremployeeassignment",
                    ),
                ),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_cells",
                        to="operations.monthlyoperationcalendar",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="day_cells",
                        to="operations.operationalposition",
                    ),
                ),
                (
                    "work_time_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="day_cells",
                        to="operations.worktimecode",
                    ),
                ),
            ],
            options={
                "ordering": ["calendar", "assignment", "date"],
            },
        ),
        migrations.AddConstraint(
            model_name="monthlyoperationcalendar",
            constraint=models.UniqueConstraint(
                fields=("department", "process", "shift", "year", "month"),
                name="unique_operation_calendar_scope_month",
            ),
        ),
        migrations.AddConstraint(
            model_name="calendaremployeeassignment",
            constraint=models.UniqueConstraint(
                fields=("calendar", "employee", "start_date"),
                name="unique_calendar_assignment_employee_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalposition",
            constraint=models.UniqueConstraint(
                fields=("department", "code"),
                name="unique_operational_position_department_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="positiondailyrequirement",
            constraint=models.UniqueConstraint(
                fields=("calendar", "position", "date"),
                name="unique_position_daily_requirement",
            ),
        ),
        migrations.AddIndex(
            model_name="calendardaycell",
            index=models.Index(
                fields=["calendar", "date"], name="operations__calenda_dcc3d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="calendardaycell",
            index=models.Index(
                fields=["position", "date"], name="operations__positio_79e51e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="calendardaycell",
            constraint=models.UniqueConstraint(
                fields=("assignment", "date"),
                name="unique_calendar_day_cell_assignment_date",
            ),
        ),
        migrations.RunPython(seed_operations_master_data, migrations.RunPython.noop),
    ]
