# Generated by Django 5.0.6 on 2026-05-23 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendaremployeeassignment",
            name="default_position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_assignments",
                to="operations.operationalposition",
            ),
        ),
        migrations.AddField(
            model_name="calendaremployeeassignment",
            name="five_two_off_days",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="calendaremployeeassignment",
            name="rotation_group",
            field=models.CharField(
                blank=True, choices=[("A", "A"), ("B", "B"), ("C", "C")], max_length=1
            ),
        ),
        migrations.AddField(
            model_name="calendaremployeeassignment",
            name="work_pattern",
            field=models.CharField(
                choices=[("4x2", "4x2"), ("5x2", "5x2"), ("manual", "Manual")],
                default="4x2",
                max_length=10,
            ),
        ),
    ]
