# Generated by Django 5.0.6 on 2026-05-24 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


ROTATION_GROUP_STYLE_SEEDS = [
    {"group_code": "A", "label": "Grupo A", "background_color": "#d9f6e5", "text_color": "#1e5138", "display_order": 1},
    {"group_code": "B", "label": "Grupo B", "background_color": "#dbeafe", "text_color": "#1e3a8a", "display_order": 2},
    {"group_code": "C", "label": "Grupo C", "background_color": "#fce7f3", "text_color": "#9d174d", "display_order": 3},
]

EMPLOYEE_VISUAL_CATEGORY_SEEDS = [
    {
        "code": "normal",
        "label_pt": "Normal",
        "label_jp": "通常",
        "target_column": "name",
        "background_color": "",
        "text_color": "",
        "print_behavior": "show",
        "display_order": 1,
    },
    {
        "code": "relief",
        "label_pt": "Ririfu",
        "label_jp": "リリーフ",
        "target_column": "kana",
        "background_color": "#fef3c7",
        "text_color": "#78350f",
        "print_behavior": "show",
        "display_order": 2,
    },
    {
        "code": "koutei_leader",
        "label_pt": "Koutei leader",
        "label_jp": "工程リーダー",
        "target_column": "code",
        "background_color": "#fef08a",
        "text_color": "#713f12",
        "print_behavior": "show",
        "display_order": 3,
    },
    {
        "code": "trainer",
        "label_pt": "Treinador",
        "label_jp": "トレーナー",
        "target_column": "code",
        "background_color": "#dcfce7",
        "text_color": "#14532d",
        "print_behavior": "show",
        "display_order": 4,
    },
    {
        "code": "retired",
        "label_pt": "Desligamento",
        "label_jp": "退職",
        "target_column": "code",
        "background_color": "#fee2e2",
        "text_color": "#7f1d1d",
        "print_behavior": "suppress_on_print",
        "display_order": 5,
    },
    {
        "code": "trainee",
        "label_pt": "Treinamento",
        "label_jp": "研修中",
        "target_column": "row",
        "background_color": "#ffe7dd",
        "text_color": "#7c2d12",
        "print_behavior": "show",
        "display_order": 6,
    },
]

OPERATIONAL_CODE_SEEDS = [
    {"code": "normal", "label_pt": "Normal", "label_jp": "通常", "category": "normal", "attendance_status": "work", "work_time_code": None, "background_color": "", "text_color": "", "affects_overtime": False, "affects_holiday_work": False},
    {"code": "teiji", "label_pt": "Teiji", "label_jp": "定時", "category": "work_time", "attendance_status": "work", "work_time_code": "regular", "background_color": "#dbeafe", "text_color": "#1e3a8a", "affects_overtime": False, "affects_holiday_work": False},
    {"code": "soutai", "label_pt": "Saida antecipada", "label_jp": "早退", "category": "attendance", "attendance_status": "early_leave", "work_time_code": None, "background_color": "#ffedd5", "text_color": "#7c2d12", "affects_overtime": False, "affects_holiday_work": False},
    {"code": "chikoku", "label_pt": "Atraso", "label_jp": "遅刻", "category": "attendance", "attendance_status": "late", "work_time_code": None, "background_color": "#fef3c7", "text_color": "#78350f", "affects_overtime": False, "affects_holiday_work": False},
    {"code": "sunday", "label_pt": "Domingo", "label_jp": "日曜", "category": "holiday", "attendance_status": "off", "work_time_code": None, "background_color": "#fce7f3", "text_color": "#9d174d", "affects_overtime": False, "affects_holiday_work": False},
    {"code": "sunday_teiji", "label_pt": "Domingo + Teiji", "label_jp": "日曜+定時", "category": "holiday", "attendance_status": "off", "work_time_code": "regular", "background_color": "#fbcfe8", "text_color": "#831843", "affects_overtime": False, "affects_holiday_work": True},
    {"code": "holiday_work", "label_pt": "Kyuujitsu shukkin", "label_jp": "休日出勤", "category": "holiday", "attendance_status": "work", "work_time_code": "holiday_work", "background_color": "#fee2e2", "text_color": "#7f1d1d", "affects_overtime": True, "affects_holiday_work": True},
    {"code": "holiday_work_teiji", "label_pt": "Kyuujitsu shukkin + Teiji", "label_jp": "休日出勤+定時", "category": "holiday", "attendance_status": "work", "work_time_code": "regular", "background_color": "#fecaca", "text_color": "#7f1d1d", "affects_overtime": True, "affects_holiday_work": True},
    {"code": "checkman", "label_pt": "Checkman", "label_jp": "チェックマン", "category": "role", "attendance_status": "work", "work_time_code": None, "background_color": "#e0e7ff", "text_color": "#312e81", "affects_overtime": False, "affects_holiday_work": False},
    {"code": "checkman_teiji", "label_pt": "Checkman + Teiji", "label_jp": "チェックマン+定時", "category": "role", "attendance_status": "work", "work_time_code": "regular", "background_color": "#c7d2fe", "text_color": "#312e81", "affects_overtime": False, "affects_holiday_work": False},
    {"code": "vaccine", "label_pt": "Vacina", "label_jp": "ワクチン", "category": "event", "attendance_status": "work", "work_time_code": None, "background_color": "#ede9fe", "text_color": "#5b21b6", "affects_overtime": False, "affects_holiday_work": False},
]


def seed_visual_and_operational_config(apps, schema_editor):
    RotationGroupStyle = apps.get_model("operations", "RotationGroupStyle")
    EmployeeVisualCategory = apps.get_model("operations", "EmployeeVisualCategory")
    OperationalCode = apps.get_model("operations", "OperationalCode")
    AttendanceStatus = apps.get_model("operations", "AttendanceStatus")
    WorkTimeCode = apps.get_model("operations", "WorkTimeCode")

    for seed in ROTATION_GROUP_STYLE_SEEDS:
        RotationGroupStyle.objects.update_or_create(
            group_code=seed["group_code"],
            defaults={**seed, "is_active": True},
        )

    for seed in EMPLOYEE_VISUAL_CATEGORY_SEEDS:
        EmployeeVisualCategory.objects.update_or_create(
            code=seed["code"],
            defaults={**seed, "is_active": True},
        )

    status_map = {item.code: item for item in AttendanceStatus.objects.all()}
    work_time_map = {item.code: item for item in WorkTimeCode.objects.all()}

    for seed in OPERATIONAL_CODE_SEEDS:
        attendance = status_map.get(seed["attendance_status"]) if seed["attendance_status"] else None
        work_time = work_time_map.get(seed["work_time_code"]) if seed["work_time_code"] else None
        OperationalCode.objects.update_or_create(
            code=seed["code"],
            defaults={
                "label_pt": seed["label_pt"],
                "label_jp": seed["label_jp"],
                "category": seed["category"],
                "attendance_status": attendance,
                "work_time_code": work_time,
                "background_color": seed["background_color"],
                "text_color": seed["text_color"],
                "affects_overtime": seed["affects_overtime"],
                "affects_holiday_work": seed["affects_holiday_work"],
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0002_calendaremployeeassignment_default_position_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeVisualCategory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("code", models.SlugField(unique=True)),
                ("label_pt", models.CharField(max_length=100)),
                ("label_jp", models.CharField(max_length=100)),
                (
                    "target_column",
                    models.CharField(
                        choices=[
                            ("name", "Name"),
                            ("kana", "Kana"),
                            ("code", "Code"),
                            ("row", "Row"),
                        ],
                        max_length=20,
                    ),
                ),
                ("background_color", models.CharField(blank=True, max_length=20)),
                ("text_color", models.CharField(blank=True, max_length=20)),
                (
                    "print_behavior",
                    models.CharField(
                        choices=[
                            ("show", "Show"),
                            ("suppress_on_print", "Suppress on print"),
                        ],
                        default="show",
                        max_length=30,
                    ),
                ),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee visual category",
                "verbose_name_plural": "Employee visual categories",
                "ordering": ["display_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="OperationalCode",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("code", models.SlugField(unique=True)),
                ("label_pt", models.CharField(max_length=100)),
                ("label_jp", models.CharField(max_length=100)),
                ("category", models.CharField(blank=True, max_length=50)),
                ("background_color", models.CharField(blank=True, max_length=20)),
                ("text_color", models.CharField(blank=True, max_length=20)),
                ("affects_overtime", models.BooleanField(default=False)),
                ("affects_holiday_work", models.BooleanField(default=False)),
                (
                    "attendance_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operational_codes",
                        to="operations.attendancestatus",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_time_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operational_codes",
                        to="operations.worktimecode",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "code"],
            },
        ),
        migrations.AddField(
            model_name="calendardaycell",
            name="operational_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="day_cells",
                to="operations.operationalcode",
            ),
        ),
        migrations.CreateModel(
            name="RotationGroupStyle",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("group_code", models.CharField(max_length=1, unique=True)),
                ("label", models.CharField(max_length=50)),
                ("background_color", models.CharField(blank=True, max_length=20)),
                ("text_color", models.CharField(blank=True, max_length=20)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "group_code"],
            },
        ),
        migrations.RunPython(seed_visual_and_operational_config, migrations.RunPython.noop),
    ]
