# Generated by Django 5.0.6 on 2026-05-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0003_employeevisualcategory_operationalcode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendardaycell",
            name="actual_overtime_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="calendardaycell",
            name="actual_work_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="calendardaycell",
            name="leave_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calendardaycell",
            name="scheduled_overtime_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="calendardaycell",
            name="scheduled_regular_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="calendardaycell",
            name="time_note",
            field=models.TextField(blank=True),
        ),
    ]
