# Generated by Django 5.0.6 on 2026-05-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0004_calendardaycell_actual_overtime_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendardaycell",
            name="break_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="calendardaycell",
            name="crosses_midnight",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="calendardaycell",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calendardaycell",
            name="manual_time_override",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="calendardaycell",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calendaremployeeassignment",
            name="shift_type",
            field=models.CharField(
                choices=[("day", "Day"), ("night", "Night"), ("flexible", "Flexible")],
                default="day",
                max_length=10,
            ),
        ),
    ]
