# Generated by Django 5.0.6 on 2026-05-27 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0006_operationcalendartemplate_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationCalendarHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("cell_date", models.DateField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("inline_edit", "inline_edit"),
                            ("quick_apply", "quick_apply"),
                            ("paste", "paste"),
                            ("fill_handle", "fill_handle"),
                            ("pattern_4x2", "pattern_4x2"),
                            ("template", "template"),
                            ("month_duplication", "month_duplication"),
                            ("next_month_generation", "next_month_generation"),
                            ("system", "system"),
                        ],
                        default="system",
                        max_length=40,
                    ),
                ),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history_entries",
                        to="operations.calendaremployeeassignment",
                    ),
                ),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_entries",
                        to="operations.monthlyoperationcalendar",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["calendar", "created_at"],
                        name="operations__calenda_0046a7_idx",
                    ),
                    models.Index(
                        fields=["calendar", "source"],
                        name="operations__calenda_c1320a_idx",
                    ),
                    models.Index(
                        fields=["calendar", "cell_date"],
                        name="operations__calenda_2cc161_idx",
                    ),
                ],
            },
        ),
    ]
