# Generated by Django 5.0.6 on 2026-05-27 07:20

from django.db import migrations


def seed_hikitsugui_categories(apps, schema_editor):
    category_model = apps.get_model("operations", "HikitsuguiOccurrenceCategory")
    seeds = [
        ("seguranca", "Segurança", "安全"),
        ("qualidade", "Qualidade", "品質"),
        ("equipamento", "Equipamento", "設備"),
        ("material", "Material", "材料"),
        ("pessoal", "Pessoal", "人員"),
        ("producao", "Produção", "生産"),
        ("manutencao", "Manutenção", "保全"),
        ("5s", "5S", "5S"),
        ("outros", "Outros", "その他"),
    ]
    for index, (code, label_pt, label_jp) in enumerate(seeds, start=1):
        category_model.objects.update_or_create(
            code=code,
            defaults={
                "label_pt": label_pt,
                "label_jp": label_jp,
                "display_order": index * 10,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0008_hikitsuguioccurrencecategory_hikitsuguireport_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_hikitsugui_categories, migrations.RunPython.noop),
    ]

