# Generated by Django 5.0.6 on 2026-05-27 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0005_alter_employee_operational_category_and_more"),
        ("operations", "0009_seed_hikitsugui_categories"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionMonitorSource",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("txt", "TXT"),
                            ("csv", "CSV"),
                            ("api", "API"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("area", models.CharField(blank=True, max_length=120)),
                ("poll_seconds", models.PositiveIntegerField(default=30)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_monitor_sources",
                        to="master.process",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductionSnapshot",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("captured_at", models.DateTimeField()),
                ("area", models.CharField(blank=True, max_length=120)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_snapshots",
                        to="master.process",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_snapshots",
                        to="master.shift",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snapshots",
                        to="operations.productionmonitorsource",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-captured_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ProductionMetrics",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("total_actual", models.IntegerField(default=0)),
                ("total_target", models.IntegerField(default=0)),
                (
                    "average_kadouritsu",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("running_count", models.PositiveIntegerField(default=0)),
                ("stopped_count", models.PositiveIntegerField(default=0)),
                ("idle_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("alarms_active", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "snapshot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="operations.productionsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-snapshot__captured_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ProductionMachineStatus",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("machine_code", models.CharField(max_length=80)),
                ("equipment_name", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("stopped", "Stopped"),
                            ("idle", "Idle"),
                            ("error", "Error"),
                        ],
                        default="idle",
                        max_length=20,
                    ),
                ),
                ("production_actual", models.IntegerField(default=0)),
                ("production_target", models.IntegerField(default=0)),
                (
                    "kadouritsu",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("run_minutes", models.PositiveIntegerField(default=0)),
                ("stop_minutes", models.PositiveIntegerField(default=0)),
                ("last_update_at", models.DateTimeField(blank=True, null=True)),
                ("alarm_active", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="machine_statuses",
                        to="operations.productionsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["machine_code", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="productionsnapshot",
            index=models.Index(
                fields=["captured_at", "process", "shift"],
                name="operations__capture_81463d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productionmachinestatus",
            index=models.Index(
                fields=["snapshot", "status"], name="operations__snapsho_04eb9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionmachinestatus",
            index=models.Index(
                fields=["machine_code"], name="operations__machine_1af5d5_idx"
            ),
        ),
    ]
