# Generated by Django 5.0.6 on 2026-05-27 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0010_productionmonitorsource_productionsnapshot_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationsSettings",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "singleton_key",
                    models.CharField(default="default", max_length=20, unique=True),
                ),
                (
                    "weekly_warning_hours",
                    models.DecimalField(decimal_places=2, default=50, max_digits=6),
                ),
                (
                    "weekly_critical_hours",
                    models.DecimalField(decimal_places=2, default=60, max_digits=6),
                ),
                (
                    "monthly_overtime_warning_hours",
                    models.DecimalField(decimal_places=2, default=45, max_digits=6),
                ),
                (
                    "monthly_overtime_critical_hours",
                    models.DecimalField(decimal_places=2, default=60, max_digits=6),
                ),
                (
                    "consecutive_absence_warning",
                    models.PositiveSmallIntegerField(default=2),
                ),
                ("recurrent_late_warning", models.PositiveSmallIntegerField(default=3)),
                ("enable_kajuuroudou_alerts", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Operations settings",
                "verbose_name_plural": "Operations settings",
                "ordering": ["id"],
            },
        ),
    ]
