# Generated by Django 5.0.6 on 2026-05-28 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0005_alter_employee_operational_category_and_more"),
        ("operations", "0011_operationssettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeAdministrativeNote",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("assiduidade", "Assiduidade"),
                            ("atraso", "Atraso"),
                            ("falta", "Falta"),
                            ("horas_extras", "Horas extras"),
                            ("kajuuroudou", "Kajuuroudou"),
                            ("orientacao", "Orientação"),
                            ("outros", "Outros"),
                        ],
                        default="outros",
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField()),
                ("related_period_start", models.DateField(blank=True, null=True)),
                ("related_period_end", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="administrative_notes",
                        to="master.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["employee", "date"],
                        name="operations__employe_05806d_idx",
                    ),
                    models.Index(
                        fields=["category", "severity"],
                        name="operations__categor_190dd0_idx",
                    ),
                ],
            },
        ),
    ]
