# Generated by Django 5.0.6 on 2026-05-28 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_operation_roles(apps, schema_editor):
    OperationRole = apps.get_model("operations", "OperationRole")

    roles = [
        ("kl", "KL / Leader", False, False, False, 10),
        ("gl", "GL / Group Leader", False, False, False, 20),
        ("supervisor", "Supervisor", False, False, False, 30),
        ("manager", "Manager", False, False, False, 40),
        ("senior_manager", "Senior Manager", False, False, False, 50),
        ("responsavel", "Responsável", True, False, False, 60),
        ("trainer_master", "Trainer Master", False, False, False, 70),
        ("hr", "HR / Staff", False, False, False, 80),
        ("director", "Director", False, False, True, 90),
        ("vice_director", "Vice Director", False, False, True, 100),
        ("viewer", "Viewer", True, False, False, 110),
        ("dashboard_tv", "Dashboard TV", True, True, False, 120),
    ]

    for code, name, is_readonly, is_dashboard_only, is_global_scope, display_order in roles:
        OperationRole.objects.update_or_create(
            code=code,
            defaults={
                "name": name,
                "is_readonly": is_readonly,
                "is_dashboard_only": is_dashboard_only,
                "is_global_scope": is_global_scope,
                "display_order": display_order,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0005_alter_employee_operational_category_and_more"),
        ("operations", "0012_employeeadministrativenote"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationRole",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("is_readonly", models.BooleanField(default=False)),
                ("is_dashboard_only", models.BooleanField(default=False)),
                ("is_global_scope", models.BooleanField(default=False)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Operation role",
                "verbose_name_plural": "Operation roles",
                "ordering": ["display_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="UserOperationProfile",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_profiles",
                        to="operations.operationrole",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User operation profile",
                "verbose_name_plural": "User operation profiles",
            },
        ),
        migrations.CreateModel(
            name="UserOperationScope",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("area", models.CharField(blank=True, max_length=120)),
                ("line", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_operation_scopes",
                        to="master.department",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_operation_scopes",
                        to="master.process",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scopes",
                        to="operations.useroperationprofile",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional override role for this specific scope.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scopes",
                        to="operations.operationrole",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_operation_scopes",
                        to="master.shift",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User operation scope",
                "verbose_name_plural": "User operation scopes",
                "ordering": [
                    "profile_id",
                    "department_id",
                    "process_id",
                    "shift_id",
                    "line",
                    "area",
                    "id",
                ],
            },
        ),
        migrations.RunPython(seed_operation_roles, migrations.RunPython.noop),
    ]
