# Generated by Django 5.0.6 on 2026-05-28 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0013_operationrole_useroperationprofile_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="useroperationprofile",
            name="additional_roles",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_profiles_additional",
                to="operations.operationrole",
            ),
        ),
        migrations.CreateModel(
            name="OperationAccessAuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("profile_updated", "Profile updated"),
                            ("scopes_replaced", "Scopes replaced"),
                        ],
                        max_length=40,
                    ),
                ),
                ("payload_before", models.JSONField(blank=True, default=dict)),
                ("payload_after", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_access_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Operation access audit log",
                "verbose_name_plural": "Operation access audit logs",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
