# Generated by Django 5.0.6 on 2026-06-02 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0014_useroperationprofile_additional_roles_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceTimecardRecord",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("employee_code_raw", models.CharField(max_length=50)),
                (
                    "employee_code_normalized",
                    models.CharField(db_index=True, max_length=50),
                ),
                ("employee_name", models.CharField(blank=True, max_length=150)),
                ("work_date", models.DateField(db_index=True)),
                ("work_type_code", models.CharField(blank=True, max_length=50)),
                ("work_type_name", models.CharField(blank=True, max_length=150)),
                ("shift_code", models.CharField(blank=True, max_length=50)),
                ("shift_name", models.CharField(blank=True, max_length=150)),
                ("clock_in", models.TimeField(blank=True, null=True)),
                ("clock_out", models.TimeField(blank=True, null=True)),
                ("total_work_minutes", models.PositiveIntegerField(default=0)),
                ("scheduled_work_minutes", models.PositiveIntegerField(default=0)),
                ("overtime_minutes", models.PositiveIntegerField(default=0)),
                ("late_minutes", models.PositiveIntegerField(default=0)),
                ("early_leave_minutes", models.PositiveIntegerField(default=0)),
                ("memo", models.TextField(blank=True)),
                ("source_file", models.CharField(max_length=255)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-work_date", "employee_code_normalized", "-id"],
                "indexes": [
                    models.Index(
                        fields=["employee_code_normalized", "work_date"],
                        name="operations__employe_04821f_idx",
                    ),
                    models.Index(
                        fields=["source_file", "work_date"],
                        name="operations__source__4a840b_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="attendancetimecardrecord",
            constraint=models.UniqueConstraint(
                fields=("employee_code_normalized", "work_date"),
                name="unique_timecard_employee_code_date",
            ),
        ),
    ]
